### ISSUE TITLE
Package license

### ISSUE THREAD

**Issue by andyone** [chifflier/nfqueue-go#1]
Hi, big thanks for your work on this package!

Sadly I can't find any information about code license. Can you please add some license file (MIT or BSD for example) to your repository?

**Comment by chifflier** [comment]
Hi,
You're right, the license file is missing (I'll add it, so I keep the bug open).
The license is GPLv2+ (this is a derivative work from libnetfilter-queue which is also GPLv2+).

**Comment by andyone** [comment]
Glad to hear that.
